#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[ERROR] .env not found. Copy .env.sample to .env and edit values."
  exit 1
fi
# shellcheck disable=SC1090
source "${ENV_FILE}"

ENABLE_CACHE_NGN=false
if [[ -n "${NGN_DNS_IPV6_1:-}" || -n "${NGN_DNS_IPV6_2:-}" ]]; then
  ENABLE_CACHE_NGN=true
fi
mkdir -p "${REPO_DIR}/config"
cat > "${REPO_DIR}/config/runtime.env" <<EOF
# Generated by scripts/01-create.sh
ENABLE_CACHE_NGN=${ENABLE_CACHE_NGN}
EOF

echo "[INFO] ENABLE_CACHE_NGN=${ENABLE_CACHE_NGN}"

render_template() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "${dst}")"
  envsubst < "${src}" > "${dst}"
}

# Base config dirs
for d in dnsdist cache-int cache-ngn auth db poweradmin quadlet systemd; do
  mkdir -p "${REPO_DIR}/config/${d}"
done

# dnsdist with optional NGN block
render_template "${REPO_DIR}/template/dnsdist/dnsdist.conf.j2" "${REPO_DIR}/config/dnsdist/dnsdist.conf.tmp"
if [[ "${ENABLE_CACHE_NGN}" == "true" ]]; then
  mv "${REPO_DIR}/config/dnsdist/dnsdist.conf.tmp" "${REPO_DIR}/config/dnsdist/dnsdist.conf"
else
  awk '/-- BEGIN_NGN/ {skip=1; next} /-- END_NGN/ {skip=0; next} skip==0 {print}' \
    "${REPO_DIR}/config/dnsdist/dnsdist.conf.tmp" > "${REPO_DIR}/config/dnsdist/dnsdist.conf"
  rm -f "${REPO_DIR}/config/dnsdist/dnsdist.conf.tmp"
fi

# cache-int with optional normal upstream forwarders
render_template "${REPO_DIR}/template/cache-int/recursor.yml.j2" "${REPO_DIR}/config/cache-int/recursor.yml.tmp"
UPSTREAMS=()
for v in "${UPSTREAM_DNS_IPV4_1:-}" "${UPSTREAM_DNS_IPV4_2:-}" "${UPSTREAM_DNS_IPV6_1:-}" "${UPSTREAM_DNS_IPV6_2:-}"; do
  [[ -n "${v}" ]] && UPSTREAMS+=("${v}")
done
if [[ "${#UPSTREAMS[@]}" -gt 0 ]]; then
  awk '/# BEGIN_UPSTREAM/ {print; next} /# END_UPSTREAM/ {next} {print}' "${REPO_DIR}/config/cache-int/recursor.yml.tmp" > "${REPO_DIR}/config/cache-int/recursor.yml"
  {
    echo '    - zone: "."'
    echo '      recurse:'
    for u in "${UPSTREAMS[@]}"; do echo "        - \"${u}\""; done
  } >> "${REPO_DIR}/config/cache-int/recursor.yml"
else
  awk '/# BEGIN_UPSTREAM/ {skip=1; next} /# END_UPSTREAM/ {skip=0; next} skip==0 {print}' \
    "${REPO_DIR}/config/cache-int/recursor.yml.tmp" > "${REPO_DIR}/config/cache-int/recursor.yml"
fi
rm -f "${REPO_DIR}/config/cache-int/recursor.yml.tmp"

# cache-ngn config
render_template "${REPO_DIR}/template/cache-ngn/recursor.yml.j2" "${REPO_DIR}/config/cache-ngn/recursor.yml.tmp"
if [[ "${ENABLE_CACHE_NGN}" == "true" ]]; then
  grep -v '# NGN_RECURSE_SERVERS' "${REPO_DIR}/config/cache-ngn/recursor.yml.tmp" > "${REPO_DIR}/config/cache-ngn/recursor.yml"
  for u in "${NGN_DNS_IPV6_1:-}" "${NGN_DNS_IPV6_2:-}"; do
    [[ -n "${u}" ]] && echo "        - \"${u}\"" >> "${REPO_DIR}/config/cache-ngn/recursor.yml"
  done
else
  rm -f "${REPO_DIR}/config/cache-ngn/recursor.yml"
fi
rm -f "${REPO_DIR}/config/cache-ngn/recursor.yml.tmp"

render_template "${REPO_DIR}/template/auth/pdns.conf.j2" "${REPO_DIR}/config/auth/pdns.conf"
render_template "${REPO_DIR}/template/db/my.cnf.j2" "${REPO_DIR}/config/db/my.cnf"
render_template "${REPO_DIR}/template/db/init.sql.j2" "${REPO_DIR}/config/db/init.sql"
render_template "${REPO_DIR}/template/poweradmin/config.inc.php.j2" "${REPO_DIR}/config/poweradmin/config.inc.php"
for f in "${REPO_DIR}"/template/quadlet/*; do
  render_template "${f}" "${REPO_DIR}/config/quadlet/$(basename "${f}")"
done
for f in "${REPO_DIR}"/template/systemd/*; do
  render_template "${f}" "${REPO_DIR}/config/systemd/$(basename "${f}")"
done
chmod 600 "${REPO_DIR}/config/db/init.sql" || true
chmod 600 "${REPO_DIR}/config/poweradmin/config.inc.php" || true

echo "[INFO] Configuration generation completed."
